name: Install packages tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker pull
      run: |
        docker login docker.pkg.github.com -u token -p ${{ secrets.READ_PACKAGES_TOKEN }}
        docker pull docker.pkg.github.com/jcansdale-test/private-repo/alpine:latest
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: |
        cat > .npmrc << EOM
        //npm.pkg.github.com/:_authToken=${{ secrets.READ_PACKAGES_TOKEN }}
        @jcansdale-test:registry=https://npm.pkg.github.com
        EOM
        npm install @jcansdale-test/private-repo
  nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dotnet add
      run: |
        dotnet new console -n HelloWorld
        cat > nuget.config << EOM
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
            <packageSources>
                <clear />
                <add key="github" value="https://nuget.pkg.github.com/jcansdale-test/index.json" />
            </packageSources>
            <packageSourceCredentials>
                <github>
                    <add key="Username" value="token" />
                    <add key="ClearTextPassword" value="${{ secrets.READ_PACKAGES_TOKEN }}" />
                </github>
            </packageSourceCredentials>
        </configuration>
        EOM
        dotnet add HelloWorld/HelloWorld.csproj package private-repo        
  rubygems:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gem install
      run: |
        cat > gemrc.yml << EOM
        :backtrace: false
        :bulk_threshold: 1000
        :sources:
        - https://token:${{ secrets.READ_PACKAGES_TOKEN }}@rubygems.pkg.github.com/jcansdale-test/
        :update_sources: true
        :verbose: true
        EOM
        gem install private-repo --install-dir . --config-file gemrc.yml
